# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2LoE2eGk5dv9VvzLHYKQbZSsPKw_jIY
"""

import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()
clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()

clean_df['Mid-Career Median Salary'].idxmax()



clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df['Undergraduate Major'][43]

clean_df.loc[43]

clean_df.loc[8]



clean_df['Starting Median Salary'].idxmin()

clean_df.loc[49]

clean_df['Mid-Career Median Salary'].idxmin()

clean_df.loc[18]



spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

spread_col.head()

clean_df.insert(1, 'Spread', spread_col)

clean_df.head()

low_risk = clean_df.sort_values('Spread')

low_risk.head()

high_pot = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)

high_pot.head()

low_risk.tail()

clean_df.groupby('Group').count()
clean_df.groupby('Group').count()

clean_df.groupby('Group').mean(numeric_only=True)

pd.options.display.float_format = '{:,.0f}'.format



clean_df.groupby('Group').mean(numeric_only=True)





